routes:
  - name: "gateway-http"
    protocol: "http"
    port: 8080
    entry:
      basePath: "/webhook"
      content_type: "json"
      compressed: false
    transform:
      remap:
      static_fields:
        source: "http"
      remove_fields:
    output:
      protocol: "file"
      file_pattern: "outputs/http_output_${DATE}.log"